using System;
using System.Collections.Generic;

namespace LSINetCore.Models
{
    public partial class LDCages
    {
        public int Id { get; set; }
        public string NumCage { get; set; }
        public decimal Longueur { get; set; }
        public decimal Profondeur { get; set; }
        public string Commentaire { get; set; }
        public int Tonnage { get; set; }
        public int TonnageMaximum { get; set; }
        public int TypeCage { get; set; }
        public string Zone { get; set; }
        public string NumCylInferieur { get; set; }
        public decimal DiametreInferieur { get; set; }
        public DateTime DateChangement { get; set; }
        public string Fournisseur { get; set; }
        public bool EnService { get; set; }
        public string NumCylSuperieur { get; set; }
        public int? TonnageVie { get; set; }
        public decimal DiametreSuperieur { get; set; }
        public DateTime? DateUsinage { get; set; }
        public DateTime? DateMiseAdisposition { get; set; }
        public DateTime? DatePremiereMiseEnService { get; set; }
        public DateTime? DateMiseEnService { get; set; }
        public string Observations { get; set; }
        public string Cannelure1 { get; set; }
        public decimal? LargeurCannelure1 { get; set; }
        public decimal? ProfondeurCannelure1 { get; set; }
        public string Cannelure2 { get; set; }
        public decimal? LargeurCannelure2 { get; set; }
        public decimal? ProfondeurCannelure2 { get; set; }
        public string Cannelure3 { get; set; }
        public decimal? LargeurCannelure3 { get; set; }
        public decimal? ProfondeurCannelure3 { get; set; }
        public string Cannelure4 { get; set; }
        public decimal? LargeurCannelure4 { get; set; }
        public decimal? ProfondeurCannelure4 { get; set; }
        public string Cannelure5 { get; set; }
        public decimal? LargeurCannelure5 { get; set; }
        public decimal? ProfondeurCannelure5 { get; set; }
        public string Cannelure6 { get; set; }
        public decimal? LargeurCannelure6 { get; set; }
        public decimal? ProfondeurCannelure6 { get; set; }
        public string Cannelure7 { get; set; }
        public decimal? LargeurCannelure7 { get; set; }
        public decimal? ProfondeurCannelure7 { get; set; }
        public string Cannelure8 { get; set; }
        public decimal? LargeurCannelure8 { get; set; }
        public decimal? ProfondeurCannelure8 { get; set; }
        public string Cannelure9 { get; set; }
        public decimal? LargeurCannelure9 { get; set; }
        public decimal? ProfondeurCannelure9 { get; set; }
        public string Cannelure10 { get; set; }
        public decimal? LargeurCannelure10 { get; set; }
        public decimal? ProfondeurCannelure10 { get; set; }
        public string Cannelure11 { get; set; }
        public decimal? LargeurCannelure11 { get; set; }
        public decimal? ProfondeurCannelure11 { get; set; }
        public string Cannelure12 { get; set; }
        public decimal? LargeurCannelure12 { get; set; }
        public decimal? ProfondeurCannelure12 { get; set; }
        public string Cannelure13 { get; set; }
        public decimal? LargeurCannelure13 { get; set; }
        public decimal? ProfondeurCannelure13 { get; set; }
        public string Cannelure14 { get; set; }
        public decimal? LargeurCannelure14 { get; set; }
        public decimal? ProfondeurCannelure14 { get; set; }
        public string Cannelure15 { get; set; }
        public decimal? LargeurCannelure15 { get; set; }
        public decimal? ProfondeurCannelure15 { get; set; }
        public decimal? Largeur2Cannelure1 { get; set; }
        public decimal? Profondeur2Cannelure1 { get; set; }
        public decimal? Largeur2Cannelure2 { get; set; }
        public decimal? Profondeur2Cannelure2 { get; set; }
        public decimal? Largeur2Cannelure3 { get; set; }
        public decimal? Profondeur2Cannelure3 { get; set; }
        public decimal? Largeur2Cannelure4 { get; set; }
        public decimal? Profondeur2Cannelure4 { get; set; }
        public decimal? Largeur2Cannelure5 { get; set; }
        public decimal? Profondeur2Cannelure5 { get; set; }
        public decimal? Largeur2Cannelure6 { get; set; }
        public decimal? Profondeur2Cannelure6 { get; set; }
        public decimal? Largeur2Cannelure7 { get; set; }
        public decimal? Profondeur2Cannelure7 { get; set; }
        public decimal? Largeur2Cannelure8 { get; set; }
        public decimal? Profondeur2Cannelure8 { get; set; }
        public decimal? Largeur2Cannelure9 { get; set; }
        public decimal? Profondeur2Cannelure9 { get; set; }
        public decimal? Largeur2Cannelure10 { get; set; }
        public decimal? Profondeur2Cannelure10 { get; set; }
        public decimal? Largeur2Cannelure11 { get; set; }
        public decimal? Profondeur2Cannelure11 { get; set; }
        public decimal? Largeur2Cannelure12 { get; set; }
        public decimal? Profondeur2Cannelure12 { get; set; }
        public decimal? Largeur2Cannelure13 { get; set; }
        public decimal? Profondeur2Cannelure13 { get; set; }
        public decimal? Largeur2Cannelure14 { get; set; }
        public decimal? Profondeur2Cannelure14 { get; set; }
        public decimal? Largeur2Cannelure15 { get; set; }
        public decimal? Profondeur2Cannelure15 { get; set; }
        public int? TonnageUsinage { get; set; }
        public DateTime? DateMiseHorsService { get; set; }
    }
}
