using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LSINetCore.Models
{
    public partial class LPBloomingProg
    {
        [Key]
        public int IdBloPprog { get; set; }
        public DateTime BloPdateCre { get; set; }
        public DateTime BloPdateMdf { get; set; }
        public string BloPmontage { get; set; }
        public int? BloPprog { get; set; }
        public double? BloPsection { get; set; }
        public double? BloPlargeur { get; set; }
        public int? BloPnbPasse { get; set; }
        public int? BloPpasse1 { get; set; }
        public string BloPcannelure1 { get; set; }
        public int? BloPpasse2 { get; set; }
        public string BloPcannelure2 { get; set; }
        public int? BloPpasse3 { get; set; }
        public string BloPcannelure3 { get; set; }
        public int? BloPpasse4 { get; set; }
        public string BloPcannelure4 { get; set; }
        public int? BloPpasse5 { get; set; }
        public string BloPcannelure5 { get; set; }
        public int? BloPpasse6 { get; set; }
        public string BloPcannelure6 { get; set; }
        public int? BloPpasse7 { get; set; }
        public string BloPcannelure7 { get; set; }
        public int? BloPpasse8 { get; set; }
        public string BloPcannelure8 { get; set; }
        public int? BloPpasse9 { get; set; }
        public string BloPcannelure9 { get; set; }
        public int? BloPpasse10 { get; set; }
        public string BloPcannelure10 { get; set; }
        public int? BloPpasse11 { get; set; }
        public string BloPcannelure11 { get; set; }
        public int? BloPpasse12 { get; set; }
        public string BloPcannelure12 { get; set; }
        public int? BloPpasse13 { get; set; }
        public string BloPcannelure13 { get; set; }
        public int? BloPpasse14 { get; set; }
        public string BloPcannelure14 { get; set; }
        public int? BloPpasse15 { get; set; }
        public string BloPcannelure15 { get; set; }
        public int? BloPpasse16 { get; set; }
        public string BloPcannelure16 { get; set; }
        public int? BloPpasse17 { get; set; }
        public string BloPcannelure17 { get; set; }
        public int? BloPpasse18 { get; set; }
        public string BloPcannelure18 { get; set; }
        public int? BloPpasse19 { get; set; }
        public string BloPcannelure19 { get; set; }
        public int? BloPpasse20 { get; set; }
        public string BloPcannelure20 { get; set; }
        public int? BloPpasse21 { get; set; }
        public string BloPcannelure21 { get; set; }
        public int? BloPpasse22 { get; set; }
        public string BloPcannelure22 { get; set; }
        public int? BloPpasse23 { get; set; }
        public string BloPcannelure23 { get; set; }
        public int? BloPpasse24 { get; set; }
        public string BloPcannelure24 { get; set; }
        public int? BloPpasse25 { get; set; }
        public string BloPcannelure25 { get; set; }
        public int? BloPpasse26 { get; set; }
        public string BloPcannelure26 { get; set; }
        public int? BloPpasse27 { get; set; }
        public string BloPcannelure27 { get; set; }
        public int? BloPpasse28 { get; set; }
        public string BloPcannelure28 { get; set; }
        public int? BloPpasse29 { get; set; }
        public string BloPcannelure29 { get; set; }
        public int? BloPpasse30 { get; set; }
        public string BloPcannelure30 { get; set; }
        public int? BloPpasse31 { get; set; }
        public string BloPcannelure31 { get; set; }
        public int? BloPpasse32 { get; set; }
        public string BloPcannelure32 { get; set; }
        public int? BloPpasse33 { get; set; }
        public string BloPcannelure33 { get; set; }
        public int? BloPpasse34 { get; set; }
        public string BloPcannelure34 { get; set; }
        public int? BloPpasse35 { get; set; }
        public string BloPcannelure35 { get; set; }
        public int? BloPpasse36 { get; set; }
        public string BloPcannelure36 { get; set; }
        public int? BloPpasse37 { get; set; }
        public string BloPcannelure37 { get; set; }
        public int? BloPpasse38 { get; set; }
        public string BloPcannelure38 { get; set; }
        public int? BloPpasse39 { get; set; }
        public string BloPcannelure39 { get; set; }
        public int? BloPpasse40 { get; set; }
        public string BloPcannelure40 { get; set; }
        public int? BloPpasse41 { get; set; }
        public string BloPcannelure41 { get; set; }
        public int? BloPpasse42 { get; set; }
        public string BloPcannelure42 { get; set; }
        public int? BloPpasse43 { get; set; }
        public string BloPcannelure43 { get; set; }
        public int? BloPpasse44 { get; set; }
        public string BloPcannelure44 { get; set; }
        public int? BloPpasse45 { get; set; }
        public string BloPcannelure45 { get; set; }
        public int? BloPpasse46 { get; set; }
        public string BloPcannelure46 { get; set; }
        public int? BloPpasse47 { get; set; }
        public string BloPcannelure47 { get; set; }
        public int? BloPpasse48 { get; set; }
        public string BloPcannelure48 { get; set; }
        public int? BloPpasse49 { get; set; }
        public string BloPcannelure49 { get; set; }
        public int? BloPpasse50 { get; set; }
        public string BloPcannelure50 { get; set; }
    }
}
